apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dodo-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USERNAME/dodo-payments-assignment.git' # Update this
    targetRevision: main
    path: task1-cluster/app-manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true